// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.4
// source: file-server/protobufs/file-metadata.proto

package file_meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *FileMetaRequest) Reset() {
	*x = FileMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_server_protobufs_file_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetaRequest) ProtoMessage() {}

func (x *FileMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_server_protobufs_file_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetaRequest.ProtoReflect.Descriptor instead.
func (*FileMetaRequest) Descriptor() ([]byte, []int) {
	return file_file_server_protobufs_file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetaRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type FileMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientIP   string `protobuf:"bytes,1,opt,name=clientIP,proto3" json:"clientIP,omitempty"`
	PortNumber int32  `protobuf:"varint,2,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
}

func (x *FileMetaResponse) Reset() {
	*x = FileMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_server_protobufs_file_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetaResponse) ProtoMessage() {}

func (x *FileMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_server_protobufs_file_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetaResponse.ProtoReflect.Descriptor instead.
func (*FileMetaResponse) Descriptor() ([]byte, []int) {
	return file_file_server_protobufs_file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetaResponse) GetClientIP() string {
	if x != nil {
		return x.ClientIP
	}
	return ""
}

func (x *FileMetaResponse) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

var File_file_server_protobufs_file_metadata_proto protoreflect.FileDescriptor

var file_file_server_protobufs_file_metadata_proto_rawDesc = []byte{
	0x0a, 0x29, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x10, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f,
	0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x46, 0x0a, 0x0a, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_server_protobufs_file_metadata_proto_rawDescOnce sync.Once
	file_file_server_protobufs_file_metadata_proto_rawDescData = file_file_server_protobufs_file_metadata_proto_rawDesc
)

func file_file_server_protobufs_file_metadata_proto_rawDescGZIP() []byte {
	file_file_server_protobufs_file_metadata_proto_rawDescOnce.Do(func() {
		file_file_server_protobufs_file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_server_protobufs_file_metadata_proto_rawDescData)
	})
	return file_file_server_protobufs_file_metadata_proto_rawDescData
}

var file_file_server_protobufs_file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_server_protobufs_file_metadata_proto_goTypes = []interface{}{
	(*FileMetaRequest)(nil),  // 0: FileMetaRequest
	(*FileMetaResponse)(nil), // 1: FileMetaResponse
}
var file_file_server_protobufs_file_metadata_proto_depIdxs = []int32{
	0, // 0: FileServer.GetFileMetaInfo:input_type -> FileMetaRequest
	1, // 1: FileServer.GetFileMetaInfo:output_type -> FileMetaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_server_protobufs_file_metadata_proto_init() }
func file_file_server_protobufs_file_metadata_proto_init() {
	if File_file_server_protobufs_file_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_server_protobufs_file_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_server_protobufs_file_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_server_protobufs_file_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_server_protobufs_file_metadata_proto_goTypes,
		DependencyIndexes: file_file_server_protobufs_file_metadata_proto_depIdxs,
		MessageInfos:      file_file_server_protobufs_file_metadata_proto_msgTypes,
	}.Build()
	File_file_server_protobufs_file_metadata_proto = out.File
	file_file_server_protobufs_file_metadata_proto_rawDesc = nil
	file_file_server_protobufs_file_metadata_proto_goTypes = nil
	file_file_server_protobufs_file_metadata_proto_depIdxs = nil
}
